import * as dotenv from 'dotenv';
dotenv.config()
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Input from '../components/input'
import Button from '../components/button'
import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY;

const supabaseClient = createClient(SUPABASE_URL,SUPABASE_ANON_KEY)

supabaseClient
  .from('users')
  .select('*')
  .then((dados) => {
    console.log(dados)
  });

export default function Home() {
  return (
    <div className={styles.container__principal}>
      <Head>
        <title>RoleCities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.titulo__principal}>RoleCities</h1>
        <form className={styles.formulario}>
          <Input label="Login" type="email" id="email" placeholder="nome@email.com"/>
          <Input label="Senha" type="password" id="password" placeholder="******" />
          <Button type="submit" id="login" content="Entrar" />
          <p className={styles.texto__padrao}>Não possui cadastro?</p>
          <a href='#' className={styles.texto__link}>Faça Aqui</a>
        </form>
      </main>
    </div>
  )
}
