import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Input from '../components/input'
import Button from '../components/button'

export default function Home() {
  return (
    <div className={styles.container__principal}>
      <Head>
        <title>RoleCities</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.titulo__principal}>RoleCities</h1>
        <form className={styles.formulario}>
          <Input label="Login" type="email" id="email" placeholder="nome@email.com"/>
          <Input label="Senha" type="password" id="password" placeholder="******" />
          <Button type="submit" id="login" content="Entrar" />
          <p className={styles.texto__padrao}>Não possui cadastro?</p>
          <a href='#' className={styles.texto__link}>Faça Aqui</a>
        </form>
      </main>
    </div>
  )
}
